services:
  - type: web
    name: statement-parser-backend
    env: python
    rootDir: .
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements_py312.txt
      mkdir -p logs
    startCommand: gunicorn api_server:app --bind 0.0.0.0:$PORT --workers 4 --timeout 120
    branch: main
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.2
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: FLASK_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: https://statement-parser-backend.onrender.com 