services:
  - type: web
    name: statement-parser-backend
    env: python
    rootDir: .
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app --bind 0.0.0.0:$PORT --workers 4 --timeout 120
    branch: render-deploy
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: https://statement-parser-backend.onrender.com
      - key: FIREBASE_SERVICE_ACCOUNT
        sync: false 