FIREBASE_API_KEY = "AIzaSyC1234567890abcdefghijklmnopqrstuv"
GOOGLE_CLIENT_ID = "123456789012-abcdefghijklmnopqrstuv.apps.googleusercontent.com"
GOOGLE_CLIENT_SECRET = "GOCSPX-abcdefghijklmnopqrstuv"
