# Firebase Web App Configuration
FIREBASE_API_KEY = "AIzaSyD21IjbFXHGym3o4oxqTS1qsRYc3jNeCuc"
FIREBASE_AUTH_DOMAIN = "loginform-jt.firebaseapp.com"
FIREBASE_PROJECT_ID = "loginform-jt"
FIREBASE_STORAGE_BUCKET = "loginform-jt.firebasestorage.app"
FIREBASE_MESSAGING_SENDER_ID = "135061333990"
FIREBASE_APP_ID = "1:135061333990:web:e4e99a1d2f80480eb55827"
FIREBASE_DATABASE_URL = "https://loginform-jt-default-rtdb.firebaseio.com/"

# Path to Firebase Service Account Key
# Replace with the actual path to your service account JSON file
FIREBASE_SERVICE_ACCOUNT_PATH = "loginform-jt-firebase-adminsdk-fbsvc-17ac4cb066.json"