[server]
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 200
maxMessageSize = 200

[browser]
gatherUsageStats = false

[theme]
base = "dark"

[client]
showErrorDetails = false
toolbarMode = "minimal"

[runner]
magicEnabled = false
installTracer = false 