# Supabase Configuration
SUPABASE_URL = "https://eoodyjpxpjswvmzdvhjr.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVvb2R5anB4cGpzd3ZtemR2aGpyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE0OTIxNzUsImV4cCI6MjA1NzA2ODE3NX0.A_BRo7rxf93l0xS6Q9n2V28qGAjP1j6qNlcxLWGh2aM"

# Postmark Configuration
POSTMARK_USERNAME = "63ff09dd-8c73-4f74-a78c-ce2601eb9fa6"  # Your Postmark Server Token
POSTMARK_SENDER = "jtsanthoshshetty0007@gmail.com"  # Your verified sender email